name: Package and build release version

on:
  push:
    tags:
      - '[0-9]+.[0-9]+.[0-9]+'
      - '!**-alpha-**'
      - '!**-beta-**'

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      GITHUB_OAUTH: ${{ secrets.GITHUB_TOKEN }}
      CF_API_KEY: ${{ secrets.CF_API_KEY }}
      WAGO_API_TOKEN: ${{ secrets.WAGO_API_TOKEN }}

    steps:
      - name: Clone project
        uses: actions/checkout@v1
        with:
          fetch-depth: 50

      - name: Create Wrath Package
        uses: BigWigsMods/packager@master
        with:
          args: -g wrath

      - name: Upload Github Actions
        uses: actions/upload-artifact@v2
        with:
          name: NDui_Plus
          path: .release/*.zip